# Generated by Django 6.0 on 2025-12-16 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Nova Análise', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('meta', 'Llama (Local/Groq)')], default='openai', max_length=20)),
                ('api_key', models.CharField(help_text='Sua chave de API para invocação', max_length=255)),
                ('model_name', models.CharField(default='gpt-4-turbo', help_text='Ex: gpt-4, claude-3-opus', max_length=50)),
                ('temperature', models.FloatField(default=0.2, help_text='0.0 a 1.0 (Menor é melhor para segurança)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário (Pentester)'), ('assistant', 'IA (PonderSec)'), ('system', 'System Prompt')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='usuarios.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
