# Generated by Django 5.2.9 on 2025-12-17 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='model_name',
            field=models.CharField(default='gemini', help_text='Ex: gpt-4, claude-3-opus', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('meta', 'Llama (Local/Groq)'), ('google', 'Gemini')], default='google', max_length=20),
        ),
        migrations.CreateModel(
            name='BlindComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_usuario', models.TextField()),
                ('resposta_gpt', models.TextField()),
                ('resposta_gemini', models.TextField()),
                ('gpt_is_option_a', models.BooleanField()),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas_restantes', models.IntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
